apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.9.1-php8.1-apache
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: wordpress-mysql
    spec:
      containers:
      - name: wordpress-mysql
        image: mariadb:10.7
        ports:
        - containerPort: 3306
        env:
          - name: "MYSQL_DATABASE"
            value: "wordpress"
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"




      