apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-web
spec:
  selector:
    matchLabels:
      app: vote-web
      tier: web
  template:
    metadata:
      labels:
        app: vote-web
        tier: web
    spec:
      containers:
      - name: vote-web
        image: ghcr.io/subicura/voting/vote:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: "REDIS_HOST"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: "POSTGRES_USER"
            value: "postgres"
          - name: "POSTGRES_PASSWORD"
            value: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: worker
        image: ghcr.io/subicura/voting/worker:latest
        env:
          - name: "REDIS_HOST"
            value: "vote-redis"
          - name: "REDIS_PORT"
            value: "6379"
          - name: "POSTGRES_HOST"
            value: "vote-postgres"
          - name: "POSTGRES_PORT"
            value: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: ghcr.io/subicura/voting/vote:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: "REDIS_HOST"
            value: "vote-redis"
          - name: "REDIS_PORT"
            value: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: ghcr.io/subicura/voting/result:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: "POSTGRES_HOST"
            value: "vote-postgres"
          - name: "POSTGRES_PORT"
            value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-np
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: vote
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: result-np
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31001
  selector:
    app: result
    tier: app



